### ISSUE TITLE
Actividad 2 Entrevista_Desarrollador de Software

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-s-b-j#1]
[Entrevista_Desarrollador de Software.pdf](https://github.com/user-attachments/files/16856135/Entrevista_Desarrollador.de.Software.pdf)

**Comment by Roldanuriel** [comment]
20/20 tiene las preguntas y respuestas bien planteadas dentro del documento así como la redacción

**Comment by josealfredo79** [comment]
bien hecho y revisado..
